### ISSUE TITLE
[BUG] Crafted Pet Carriers vanish when used on a pet

### ISSUE THREAD

**Issue by Lurrae** [Mnesikos/SimplyCats#13]
**Describe the bug**
When a player crafts a Pet Carrier and uses it on their pet, they receive a message above their hotbar saying the pet was retrieved, and the pet carrier vanishes from their inventory immediately thereafter.

**To Reproduce**
1) Open Minecraft 1.16.5 with Simply Cats 0.1.2
2) Craft a brand new pet carrier, and use it on a cat from Simply Cats
3) The game will display the message saying "Pet Retrieved!" and the pet carrier will vanish entirely, alongside the pet itself

**Expected behavior**
When a crafted Pet Carrier is used on a pet, it should remain in the player's inventory, with updated NBT data as necessary.

**Logs (REQUIRED)**
latest.log after entering the world, crafting a pet carrier, and using it: https://pastebin.com/WjGU7DCu
(Note: I tried to get debug.log as well, but it was too big for Pastebin, so hopefully just having latest.log here is okay ^-^;)

**Screenshots**
![2021-11-06_15 04 50](https://user-images.githubusercontent.com/69269327/140622451-78e019d1-2b8f-4ed8-a3fc-fb126dde5958.png)
![2021-11-06_15 05 05](https://user-images.githubusercontent.com/69269327/140622452-df074d75-47c0-494b-b948-2337a9f70c02.png)

**Versions (please complete the following information):**
 - Minecraft 1.16.5
 - Forge 36.2.9
 - Simply Cats 0.1.2
 - Full modlist, including versions:
![modlist_1](https://user-images.githubusercontent.com/69269327/140622469-c795ded9-eb7a-449a-abf2-9053c8bf0a9e.png)
![modlist_2](https://user-images.githubusercontent.com/69269327/140622472-435b5cfa-8899-49c6-9666-a3deb2376b9f.png)

**Additional context**
Pet Carriers bought from the Shelter also vanish, but according to a friend who has played with the mod before, this is intentional behavior (though crafted Pet Carriers should not vanish according to them)
Also, I have not tested this on dogs yet, but I assume it works the same for them too

**Comment by IceaPlayzPC** [comment]
Friends with Tepig, i will note that this does not seem to happen in creative mode, but my modlist is very different. if needed i can try reproducing the bug as well and sharing my modlist

**Comment by IceaPlayzPC** [comment]
Update: i tested on my world, the same thing happened. Carriers and cats remained in creative mode, but in survival mode, they disappeared, so i think we  can rule out  conflicting mods and chalk it up to the carriers disappearing function being activated when crating cats.

**Comment by Mnesikos** [comment]
Oh no!! Definitely a bug I didn't know we had but is not good for survival play. I'm away from my computer all weekend, but will fix this asap Monday night. Thank you so much for reporting this.

**Comment by Lurrae** [comment]
No problem! I'm glad we could help!

**Comment by Mnesikos** [comment]
Just fixed this, so sorry for the wait! 0.1.3 is being approved on curseforge right now.
