### ISSUE TITLE
heat cooldown skip item?

### ISSUE THREAD

**Issue by TuffCat** [Mnesikos/SimplyCats#15]
hey so i'd just like to suggest a good feature idea.
i'm very tired with having to wait for a female cat with good genetics to finish her heat cooldown. especially when the wait is over a half hour long. i'd like to suggest a creative-only item that automatically skips the female heat cooldown. i think it would be useful for people trying to get a cat with good genetics and going past multiple generations, that don't want to be working for 8 hours straight.

**Comment by Mnesikos** [comment]
Use blaze powder! It's listed on this wiki page, at the bottom: <https://github.com/Mnesikos/SimplyCats/wiki/Cats>

**Comment by TuffCat** [comment]
ah thank you!
