### ISSUE TITLE
[BUG] Low Shelter Spawn rates and No Shelter Cats

### ISSUE THREAD

**Issue by TuffCat** [Mnesikos/SimplyCats#17]
**Describe the bug**
Villages rarely spawn with shelters, and shelters do not contain animals at all. Shelters also only spawn in desert/savannah biomes, as far as I can tell. Out of 8 villages, only 2 of them had shelters, and none had any pets.

**To Reproduce**
Simply open a new world with the latest version of the mod, and keep looking around the world using the "/locate village" command to find villages and you will see that only desert/savannah villages have shelters, and none of them have any pets in them.

**Expected behavior**
I expected that at least 6 out of 8 of those villages to have shelters, and for all of them to have pets in them.

**Logs (REQUIRED)**
Ah, sorry, no crash report! It doesn't crash the game, it's just extremely annoying and bad that survival players will almost never be able to get cats from this mod.

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.34
 - Simply Cats: Newest Version, aka 0.1.3
 - list all other mods in the pack with the crash (a screenshot is okay): Alex's Mobs, Citadel 1.8.1, Easy Breeding, Genetic Animals, Give Me Water or Give Me Death, Realistic Horse Genetics, Simply Cats(of course), skds core(to support water physics mod), Water Physics Overhaul, WPO Addon Mod

**Additional context**
I would love to see this fixed quickly! I think that the thing with not finding many shelters is just that you don't have models for the other shelters- or the probability is too low. I have NO idea what's happening with the pets in the shelters, though.

**Comment by TuffCat** [comment]
i didn't think that editing it would actually make something new- well i guess i close this now

**Comment by Mnesikos** [comment]
Shelter spawn rates were set based on just having Simply Cats installed. If you are using other mods, specifically ones that also edit villages, there will be differences. I suggest looking into the Repurposed Structures mod and their datapacks for mod compatibility. (<https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-simply-cats-datapack-compat>)

Currently in the 1.16.5 version, dogs and cats were not added to the shelters, so it's not a bug at the moment, just an incomplete feature. They will be added back eventually.

**Comment by TuffCat** [comment]
well i don't have any mods that affect villages. could i possibly unzip the .jar file and change the config for the shelter spawn rate?
