### ISSUE TITLE
[BUG] random heat end with only 4 kittens???

### ISSUE THREAD

**Issue by TuffCat** [Mnesikos/SimplyCats#20]
**Describe the bug**
i bred two cats. your standard black tabby mom, ginger tabby father. at first, the mother was not breeding. and yes she was in heat and the father did not have a cooldown. FINALLY, the mom got pregnant. above her name tag, it didn't say she was in heat. i assumed this meant she would have kittens. i gave her some blaze powder, and waited. then she had her kittens- but she had only 4?!

**To Reproduce**
i genuinely can't tell how this happened- so sorry!

**Expected behavior**
i expected her to have 6 kittens, since she wasn't in heat anymore.

**Logs (REQUIRED)**
no logs, sorry!

**Versions (please complete the following information):**
i'm kinda lazy so u can look at my other bug reports-

**Comment by Mnesikos** [comment]
Read the breeding page of the wiki, this is not a bug.

**Comment by TuffCat** [comment]
oh. i thought it said that heat auto-ends with 6 kittens, also a little thing, can you lower the chance that a mating fails? it happens way too often. another weird thing is that sometimes, a female- in heat- and a male- no cooldown- will refuse to breed. it's really weird and super annoying that i have to skip through multiple heats with the female for it to work.

**Comment by Mnesikos** [comment]
Yes, it will automatically end if the 6 kitten mark is reached, as that's the maximum possible. Read it again and you'll see it also says there is a 25% chance the mother's heat ends.

If two breedable cats are not breeding while they meet the breeding requirements, then that is a separate bug itself and you should create a report for that specifically- including your latest and debug log files. Please go back over the wiki's breeding page with a fine tooth comb first to make sure you're not missing something else.
