### ISSUE TITLE
custom textures?

### ISSUE THREAD

**Issue by TuffCat** [Mnesikos/SimplyCats#22]
so i've looked in the extracted jar file and i've seen some 'custom textures'. i'm assuming that it's one of those things where you name a mob and it has a custom texture. i tried naming one penny and it didn't work? can you please explain how these custom textures work?

**Comment by Mnesikos** [comment]
Those are *private* custom textures, assigned to the mimecraft user's UUID for only them to use.

Please don't open mod jar files in the future, that is not how they're meant to be used.
