### ISSUE TITLE
[BUG] Cats not interacting with food items

### ISSUE THREAD

**Issue by DoveGirl777** [Mnesikos/SimplyCats#27]
**Describe the bug**
I placed a food bowl, dish and furniture items and the cat isn't using them. The food stays in the bowl and water stays in the other bowl.

**To Reproduce**
I place the food bowls down
the cats do not interact with them for a minecraft day

**Screenshot's**
[https://postimg.cc/zV9xdTsF](url)
**Versions:**
 - Minecraft 1.12.2
 - Forge 14.23.5.2855
 - Simply Cats 0.2.2

**Additional context**
The game did not crash, its just that the cats aren't interacting with the food bowls, and furniture

**Comment by TuffCat** [comment]
they don't interact with them, the feature hasn't been implemented yet

**Comment by DoveGirl777** [comment]
Oh.... thank you

**Comment by TuffCat** [comment]
np! mnes is still adding a couple things to the mod, at some point food bowl functionality will be added(i think)

**Comment by Mnesikos** [comment]
As per the wiki page for bowls, (https://github.com/Mnesikos/SimplyCats/wiki/Bowl), they do not have any functionality; however, I have no immediate plans or intentions to change that. They're an aesthetic decoration. Please excuse the misinformation from TuffCat.
