### ISSUE TITLE
[BUG] White Markings randomly change

### ISSUE THREAD

**Issue by PuppeteerLoyals** [Mnesikos/SimplyCats#28]
**Describe the bug**
I was messing around with the summoning and whenever I would summon a cat with the supposed white markings, but then they suddenly change to having a completely different pattern of the white markings. 

**To Reproduce**
Summon a cat of any kind with the Ws-Ws gene

**Expected behavior**
A cat will spawn with one form of white markings, and a little bit later will turn into a completely different form of white markings

**Versions (please complete the following information):**
 - Minecraft [1.16.5]
 - Simply Cats [0.2.2]

**Comment by Mnesikos** [comment]
So, the summon command is not great for white markings and I honestly probably won't dig much deeper to try to remedy it. (The summon command has been a huge pain in the butt... lol.)

If you summon a cat, try picking them up with a pet carrier and placing them back down to get their white markings working properly. Sorry for the inconvenience!
