### ISSUE TITLE
[BUG] Cats not breeding 1.16.5

### ISSUE THREAD

**Issue by FallenMorgan** [Mnesikos/SimplyCats#31]
Have females in heat and males available all intact and they not want breed I tried change they location and increase size of the location but they not want to breed not know why https://imgur.com/a/TbJUcL1

**Comment by Mnesikos** [comment]
In the future, follow the bug issue template provided. What version of Simply Cats, Forge, and Minecraft are you using?

Have you read through the [breeding page](https://github.com/Mnesikos/SimplyCats/wiki/Breeding) on the wiki?

**Comment by FallenMorgan** [comment]
> In the future, follow the bug issue template provided. What version of Simply Cats, Forge, and Minecraft are you using?
> 
> Have you read through the [breeding page](https://github.com/Mnesikos/SimplyCats/wiki/Breeding) on the wiki?

yes everything that breeding guide says I did and I using simple cats most recently version 0.2.2 for 1.16.5 and forge version Recommended version 1.16.5 - 36.2.34

**Comment by FallenMorgan** [comment]
[Mnesikos](https://github.com/Mnesikos) well I told up here versions and stuff

**Comment by FallenMorgan** [comment]
[Mnesikos](https://github.com/Mnesikos) I gonna remake the bug topic to be easy to you figure out
