### ISSUE TITLE
[BUG] Pet Carrier Doesn't Show Up When Crafted

### ISSUE THREAD

**Issue by AKJENebbie916** [Mnesikos/SimplyCats#35]
**Describe the bug**
Pet carrier doesn't show up on latest mod update (7/28/2022 1.16.5 0.2.2) when I craft one. I can't grab it, it is not just invisible. I'm crafting them correctly, 1 iron bar, 4 iron ingots, 4 terracottas.

**To Reproduce**
Steps to reproduce the behavior: Craft using 1 iron bar, 4 iron ingots, and 4 terracottas.

**Expected behavior**
A Pet Carrier is supposed to show up.

**Logs (REQUIRED)**
[debug.log](https://github.com/Mnesikos/SimplyCats/files/11684911/debug.log)
[latest.log](https://github.com/Mnesikos/SimplyCats/files/11684912/latest.log)

**Screenshots**
![PetCarrierBug](https://github.com/Mnesikos/SimplyCats/assets/110153227/f383682d-d846-48e0-9c32-79dec0f53dc7)

**Versions (please complete the following information):**
 - Minecraft [e.g. 1.16.5]
 - Forge [e.g. 36.2.20]
 - Simply Cats [e.g. 0.2.2]
 - list all other mods associated with the pack that crashed (a screenshot is okay)

**Additional context**
Biomes O Plenty

**Comment by Mnesikos** [comment]
Use regular terracotta, not a colored version
