### ISSUE TITLE
cat spawned from spawn egg not tameable

### ISSUE THREAD

**Issue by Dolphinways** [Mnesikos/SimplyCats#36]
i spawned a cat from a spawn egg and cannot tame it with cod/fish

**To Reproduce**
-go into creative mode
-spawn a cat via spawn egg
-right click while looking at cat with fish/cod

**Expected behavior**
either black smoke effect to eventually hearts indicating taming

**Logs**
https://pastebin.com/BiYX2Kbe

**Versions**
 - Minecraft [e.g. 1.16.5]
 - Forge [36.1.0]

Architectury API (Fabric/Forge)

Biomes O' Plenty

Dynamic Lights Extended

**Simply Cats**

WorldEdit

WTHIT Forge Edition

Xaero's Minimap

Alex's Mobs

OptiFine
(optifine with redhat shaders)

**Comment by Mnesikos** [comment]
Hi! That's not how this mod works, this is not a bug. Please read the wiki.

**Comment by Dolphinways** [comment]
well anyway i fixed it anyway by removing husbandry so uh
