### ISSUE TITLE
Kittens won't grow up.

### ISSUE THREAD

**Issue by Tuckamore** [Mnesikos/SimplyCats#7]
it has been more than seven Minecraft days so I changed the number of Ticks needed to have them mature to a much lower number. None of them have grown up, not even the kitten I've had since the beginning and that kitten is much older than the rest. I am not sure if it is because of the other mods I have or something similar but they just aren't aging up.

**Comment by Mnesikos** [comment]
Posted this in discord, but for the sake of github I'll post here too:
This has gotta be one of the strangest issues I've heard of so far
Whenever you're around next, could you post maybe your list of mods and SC config? Either here (discord) or on the github issue!
I'm also thinking it could have something to do with the kittens being unloaded. If you're exploring elsewhere and the chunks with the kittens become unloaded, their timers won't move at all.

**Comment by Tuckamore** [comment]
Yeah, it could be the unloading thing but I can send the list of mods:
Astral sorcery
Baubles
Biomes-o-plenty
bonsai trees
bookworm
crayfish furniture mod
exotic birds
fairy lights mod
fossil archeology
Heres What You're Looking At
Ice And Fire
Improved Backpacks
Just Enough Items
Journey Map
Lighting wand
Minecraft Comes Alive
Mclib
Natures Compass
Optifine
Pam's Harvest Craft
Thaumcraft
Tree Chopper
Ultimate Unicorn Mod
ZAWA
Sorry for such a long list!

**Comment by Mnesikos** [comment]
Seems to have been an issue of unloaded chunks, all is well!
