### ISSUE TITLE
Carrying Box Crashes the world and game

### ISSUE THREAD

**Issue by Meg326** [Mnesikos/SimplyCats#9]
When I put a cat to carrying box and then release it the game crashes and I can't get back to my world

**Comment by Mnesikos** [comment]
This needs more information, I can't do anything with this.

**Comment by Meg326** [comment]
> This needs more information, I can't do anything with this.

I solved the problem later it was becuase of my extra big modpack probably an incompatible mod was there that made my game crash. I tried in a more little pack and problem solved
